services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel_collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4318:4318" # OTLP HTTP receiver
      - "4317:4317" # OTLP gRPC receiver
      - "8889:8889" # Prometheus exporter port
    depends_on:
      jaeger:
        condition: service_started # Jaeger can start whenever
      clickhouse:
        condition: service_healthy # Wait for ClickHouse healthcheck
    restart: on-failure
    command: ["--config=/etc/otelcol-contrib/config.yaml"]

  jaeger:
    image: jaegertracing/all-in-one:1.52.0
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true  # Включаем OTLP приемник]
    ports:
      - "6831:6831/udp" # Jaeger agent (для приема Thrift compact)
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Jaeger collector (для приема Thrift HTTP)
      - "14250:14250" # Jaeger collector (для приема gRPC)
    depends_on:
      clickhouse:
         condition: service_healthy # Jaeger might also need ClickHouse ready for UI/API features
      # If you switched Jaeger to Cassandra, add that dependency here too:
      # cassandra:
      #   condition: service_healthy
    restart: on-failure # Restart if it fails

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native interface
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./migrations/clickhouse/clickhouse-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migrations/clickhouse/clickhouse-users.xml:/etc/clickhouse-server/users.d/users.xml
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_DB=otel_logs
      - CLICKHOUSE_LOG_LEVEL=trace
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck: # Added healthcheck
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s # Give ClickHouse time to start before checking

  prometheus: # New Prometheus service
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      otel-collector: # Wait for otel-collector to start
        condition: service_started
    restart: on-failure
    command: ['--config.file=/etc/prometheus/prometheus.yml', '--storage.tsdb.path=/prometheus']

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=xx
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/dashboards
    depends_on: # Grafana should start after Prometheus is available
      - prometheus
      # - clickhouse # If Grafana also depends on Clickhouse, keep it

volumes:
  grafana-data:
  postgres-data:
  clickhouse-data:
  prometheus-data: # Add volume for Prometheus data
  # cassandra-data: # Keep if Jaeger uses Cassandra