services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel_collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4318:4318" # OTLP HTTP receiver
      - "4317:4317" # OTLP gRPC receiver
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.52.0
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true  # Включаем OTLP приемник
    ports:
      - "6831:6831/udp" # Jaeger agent (для приема Thrift compact)
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Jaeger collector (для приема Thrift HTTP)
      - "14250:14250" # Jaeger collector (для приема gRPC)
  
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml


volumes:
  grafana-data:
  postgres-data: