receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  debug: # this will export data to the console
    verbosity: detailed # without this we won't be able to see the log
  otlp: # Используем тип экспортера 'otlp'
    endpoint: "jaeger:4317"
    tls: # Добавляем конфигурацию TLS
      insecure: true # Отключаем TLS, используем незашифрованное соединение
  clickhouse:
    endpoint: http://clickhouse:8123
    database: otel_logs 
    logs_table_name: logs
    username: default
    password: ""
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
  prometheus: # Added Prometheus exporter
    endpoint: "0.0.0.0:8889"

processors:
  batch:
  resource:
    attributes:
      - key: service.name
        value: "go-app"
        action: upsert

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug, clickhouse]
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug, prometheus]
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug, otlp]