{
 "title": "Go Runtime(RAW)",
 "description": "Dashboard for Golang builtin Host & Runtime metrics",
 "tags": [
  "go",
  "host",
  "runtime"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "exported_job",
    "label": "exported_job",
    "query": {
     "query": "label_values({exported_job=\"$exported_job\"},exported_job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "cpu - system seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "system_cpu_time_seconds_total{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu - process seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "process_cpu_time_seconds_total{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - system utilization ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_utilization_ratio{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - system usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_usage_bytes{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - process idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_idle_bytes{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - process alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_alloc_bytes{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - process inuse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_inuse_bytes{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - process released",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_released_bytes{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - heap sys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_sys_bytes{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - live objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "process_runtime_go_mem_live_objects{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - heap objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_objects{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mem - lookups total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "process_runtime_go_mem_lookups_total{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network - io total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_network_io_bytes_total{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "uptime - total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "runtime_uptime_milliseconds_total{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cgo - calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "process_runtime_go_cgo_calls{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "process_runtime_go_goroutines{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gc - total count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "process_runtime_go_gc_count_total{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gc - pause ns bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "targets": [
    {
     "expr": "process_runtime_go_gc_pause_ns_bucket{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gc - pause ns sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "process_runtime_go_gc_pause_ns_sum{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gc - pause ns count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "targets": [
    {
     "expr": "process_runtime_go_gc_pause_ns_count{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gc - pause ns total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "process_runtime_go_gc_pause_ns_total{exported_job=\"$exported_job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}