apiVersion: 1

datasources:
  - name: jaeger
    type: jaeger
    uid: jaeger
    url: http://jaeger:16686
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'clickhouse'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: ['job', 'instance', 'pod', 'namespace']
        filterByTraceID: true
        filterBySpanID: false
      nodeGraph:
        enabled: true
        
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      defaultDatabase: otel_logs
      defaultTable: logs
      host: clickhouse
      port: 9000
      username: default
    secureJsonData:
      password: ""
  

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
    isDefault: true
