apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    uid: jaeger
    url: http://jaeger:16686
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'clickhouse'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: ['job', 'instance', 'pod', 'namespace']
        filterByTraceID: true
        filterBySpanID: false
      nodeGraph:
        enabled: true
        
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    url: http://clickhouse:8123
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      defaultDatabase: otel_logs
      defaultTable: logs
      username: default
    secureJsonData:
      password: ""
